### ISSUE TITLE
meta element

### ISSUE THREAD

**Issue by 3052** [havenweb/haven#119]
is it possible to specify a meta element?

https://developer.mozilla.org/docs/Web/HTML/Element/meta

**Comment by mawise** [comment]
Today there is no way to specify a meta element.  Usually those elements are useful for public webpages to tell search engines and other websites what is on a page.  Since Haven is private, this shouldn't be required.  Why do you want to specify meta elements?

**Comment by 3052** [comment]
oh wow my bad I didn't realize its private blog - thats not at all what I am wanting
