### ISSUE TITLE
"No video with support format and MIME type found." when uploading video

### ISSUE THREAD

**Issue by rlglenn** [havenweb/haven#126]
Using Firefox with account on https://demo.havenweb.org, uploaded mp4 video, video controls tag and type="video/mp4" automatically created, but video does not play and get a message: "No video with support format and MIME type found." Am I doing something wrong, or is video not supported?

**Comment by mawise** [comment]
Video is supported, I just did a test on the running demo and it worked.  I suspect it has to do with something like the specific encoding format your video uses.  Would you feel comfortable attaching your video to the github issue or otherwise sharing it so I can investigate further?

**Comment by mawise** [comment]
Without additional information I'm afraid I can't debug this any further.

**Comment by skycorrigan** [comment]
@mawise I'm having a video upload problem of my own. I can upload an 8 minute video from my desktop to my Haven instance (sits behind nginx proxy manager in a docker container) but I get an error when I try to upload even a 3 second video from my phone to the same Haven instance. 

The 8 minute video is in 1080P and the 3 second video is in 720P (purposely used low resolution for testing after initial 1080P error from phone). I've attached the video, video details, and corresponding video upload area screenshots. If you or anyone else could help I'd really appreciate it.


https://github.com/user-attachments/assets/efba749e-7963-455f-bc6f-f5031872a18d

![IMG_2337](https://github.com/user-attachments/assets/da23eae7-de69-44b5-a3ed-85721a118985)
![IMG_2338](https://github.com/user-attachments/assets/59bcb5a8-e3cd-4148-8663-d50c559c1c72)

**Comment by mawise** [comment]
Thank you for the sample video!  This video doesn't work because it is a `.mov`.  Haven currently expects videos to be `.mp4`.  I'll leave some notes for myself from the error logs here.  I think I can fix this soon.

```
F, [2024-12-30T13:38:46.734654 #29150] FATAL -- : [e4a65eb0-dd8c-46f3-9a4c-dfd4127c5e93]
[e4a65eb0-dd8c-46f3-9a4c-dfd4127c5e93] NoMethodError (undefined method `>' for nil:NilClass

    if image_meta[:width] > 1600 #resize at lower quality with link
                          ^):
[e4a65eb0-dd8c-46f3-9a4c-dfd4127c5e93]
[e4a65eb0-dd8c-46f3-9a4c-dfd4127c5e93] app/controllers/posts_controller.rb:164:in `process_new_image'
[e4a65eb0-dd8c-46f3-9a4c-dfd4127c5e93] app/controllers/posts_controller.rb:208:in `handle_form_submit'
[e4a65eb0-dd8c-46f3-9a4c-dfd4127c5e93] app/controllers/posts_controller.rb:65:in `create'
```

**Comment by skycorrigan** [comment]
Is there anyway to allow Haven to process videos in .mov format, as that's the format that they are recorded into on iOS devices. Would be great for uploading to Haven straight from the iOS devices vs having to convert elsewhere and upload from there.

**Comment by skycorrigan** [comment]
@mawise Hello again. I just saw that you added support for MOV video file. Thank you. Unfortunately it doesn't look like it's working (for me at least) as I still get the "we're sorry, but something went wrong" error message attempting an upload.

I've done a git pull to update and restarted the container for few times but I still get the error. Any advice?
