### ISSUE TITLE
No License in the project

### ISSUE THREAD

**Issue by jalal246** [havenweb/haven#2]

**Comment by mawise** [comment]
I haven't decided on a license yet.  I want to consult with a legal expert before making that decision.  Until then, I'll explicitly say that anyone is free to use this for personal purposes, free to distribute it as-is (so long as these freedoms are retained in the distribution) and free to make changes so long as if distributed, those changes are made clear.

I'll keep this issue open until I've settled on a more formalized license.

**Comment by mawise** [comment]
I've adopted a the MIT license for Haven.  Closing this issue.
