### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by selfhosted-heaven** [havenweb/haven#24]
I believe the project could greatly benefit from Docker (and compose) support. Making it easier to setup on machines that are not single purpose (like a raspberry pi or AWS instances) can be greatly beneficial in getting a greater adoption for Haven. 

We can start with a rough base and refine from there.

**Comment by DrMxrcy** [comment]
Plans to add ARM Support?

**Comment by mawise** [comment]
Hey @DrMxrcy , Haven should work fine on ARM, I've run it as bare-metal on 32-bit and 64-bit Raspberry Pis.  The ruby Docker image I started with [claims to be cross-platform and support ARM](https://hub.docker.com/_/ruby/).  Do you want to try it out and let me know if you run into any issues?

**Comment by DrMxrcy** [comment]
> Hey @DrMxrcy , Haven should work fine on ARM, I've run it as bare-metal on 32-bit and 64-bit Raspberry Pis. The ruby Docker image I started with [claims to be cross-platform and support ARM](https://hub.docker.com/_/ruby/). Do you want to try it out and let me know if you run into any issues?

Sounds good. Just wanted to make sure it would. I will test it out, but you could also look at [buildx ](https://github.com/marketplace/actions/docker-buildx)to push to arm as well.  I will double check it later this week

**Comment by DrMxrcy** [comment]
@mawise Yea I did a quick look, the docker image has to be build for arm.

**Comment by mawise** [comment]
Got it, Ill take a look but it might be a little while.  Feel free to
submit a PR for multi-arch builds!

**Comment by mawise** [comment]
Hey @DrMxrcy ,

Looks like using buildx to push to Docker Hub from Github Actions requires a paid Docker Hub account, so I'm not going to set that up right now.  (Nothing buildx-specific, but the CI integration with Github they restrict to the paid tier).

If you know anyone at Docker who wants to give me a complimentary Pro tier account then I'd be happy to set it up.

Cheers,

Matt

**Comment by mawise** [comment]
Closing this issue as the title is more about Docker support which exists now.  @DrMxrcy feel free to open a new issue for better multi-arch support.
