### ISSUE TITLE
TicketAuth support?

### ISSUE THREAD

**Issue by fluffy-critter** [havenweb/haven#29]
Hi, there's been some pretty great strides in support for [IndieAuth Ticket Auth](https://indieweb.org/IndieAuth_Ticket_Auth) which is a simple mechanism for publishers to provide a bearer authentication token to clients (such as feed readers), which is [significantly more secure than private per-user feeds](http://publ.plaidweb.site/blog/1266-Why-Publ-wont-support-magic-auth-links). Are there any plans to support that on the reader and/or publisher side of Haven?

Getting more widespread adoption of this mechanism would be great.

**Comment by mawise** [comment]
I've definitely thought about IndieAuth-based approaches for several things and it's in my plan for further development.  At the initial stage, I'd like to provide some level of compatibility with existing feed-readers, which brought me to http basic auth.

The link you shared highlighting the risks of Atom item sharing is new to me.  Do you know anything else about this?  From the article I can't tell if they are using a credential as a query/url parameter, or with HTTP Basic Auth.  Haven uses basic auth.  This means that feed credentials *should* obviously be credentials to any feed reader, but anytime you entrust credentials to third-party software you're taking a risk.  Newsblur for example has a habit of assuming feeds are public and making them publicly visible as soon as 3 or more people are subscribed to the same feed.

Do you know of any feed readers (or feed publishers) that currently support TicketAuth for accessing private feeds?

**Comment by fluffy-critter** [comment]
I'm the author of that linked article. I was specifically speaking to the situation of using a private per-user feed, e.g. `https://example.com/feed/327982acbaf38bf` or the like; any tokens stored in the URL will be leaked if an item is shared in an Atom context (whether the item is private or not).

I don't know of any feed readers which support bearer tokens yet although there's a few IndieWeb folks working on them right now, such as omz13 and David Shanske, and I have plans to write one as well (although I haven't had the time/energy to actually start on it).

HTTP Basic Auth is an interesting approach. How well does that work with existing feed readers? I wasn't aware that there were any major aggregating readers that supported it, although I can see it working well with things like Firefox Live Bookmarks, and presumably Haven supports it as well. In any case I'd think that sending a stored bearer token shouldn't be terribly different than sending a stored basic auth string, and the only "hard" part about TicketAuth is supporting the ticket exchange itself.

And yeah the privacy implications of a shared feed subscription are pretty onerous, which is why I think that a reader with bearer token support needs to be built with that in mind from the ground up (which is absolutely what I'm planning if I ever get around to writing [Subl](https://github.com/PlaidWeb/Subl)). There's also some subtle implications on how WebSub works in an authenticated world, especially when using third-party hubs; basically you need the hub to support "thin pings" (which are technically not in the WebSub spec but I think most readers work with them anyway).

If you ever want to test implementing bearer token support, you could get one for my blog feed; my site has a [user profile page](https://beesbuzz.biz/profile) where you can fetch one for manual inclusion, and then you can test bearer tokens without needing to implement the full TicketAuth flow.

**Comment by mawise** [comment]
Closing this.  I'm sticking with RSS for broader compatibility for now but may explore TicketAuth at another point.

**Comment by fluffy-critter** [comment]
TicketAuth is an addition to RSS, not in opposition to it.

**Comment by mawise** [comment]
Except for my time!

**Comment by fluffy-critter** [comment]
Yes, totally understandable! It's just that the way you phrased the close message made it sound like RSS is different than TicketAuth, rather than TicketAuth being a means of providing authentication to RSS.
