### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by farleykr** [havenweb/haven#3]
Do you plan on adding contribution guidelines?  I would love to help out where possible if there's a need and/or desire for contributions.  If not, no worries.  Just wanted to get the conversation going if there's one to be had.

**Comment by mawise** [comment]
Thanks for the offer!  I haven't thought much about organizing Haven as a community project.  I'll reach out to you directly and we can chat a little bit.

If anyone else is interested in contributing feel free to chime in here as well!

**Comment by mawise** [comment]
I haven't had any more interest in community contributions so I'm closing this issue for now.
