### ISSUE TITLE
own reverse proxy

### ISSUE THREAD

**Issue by betov69** [havenweb/haven#32]
Hello, good day, I am trying to get Haven to work with the deploy-pi.sh script, however, I have some doubts, I have my own reverse proxy to expose the server to the internet, which part of the script would I have to delete for everything to work ok, try removing the parts of:

```

## HTTPS with Letsencrypt
#Rewrite Apache config to fix http -> https redirect

```
However, I get a server not available error, could you guide me a little, thanks

**Comment by mawise** [comment]
It depends on your setup.  When I've done it this way before, I need to have the reverse proxy handle SSL and serve the HTTPS certificate.  That means you're setting up Haven as a raw HTTP server (no HTTPS).

The sections you've removed are what I would suggest, do you have any more specific errors from your reverse proxy's logs, from the apache logs on the pi, or from the Haven logs (/var/www/haven/logs/) ?

**Comment by betov69** [comment]
Hello, thank you for responding as soon as I have checked the path of the log file and there is no file, it keeps sending the error, 503 really what I would like is to have the server in http to be able to use my reverse proxy, the other option that occurs to me is install everything from scratch without the script the steps would be:

-install dependencies:

sudo apt-get install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev git libgdbm6 libreadline-dev bcrypt

-Clone Ruby (not sure if this part is necessary)

-Install NodeJS and Yarn

-Install Imagemagick

-Install Apache and PostgreSQL

-Install Rails App (Haven)

-Create the service simpleblog.service

-Start and enable the service

So far it would be possible to start Haven WITHOUT https and domain?

Thanks and regards

**Comment by mawise** [comment]
Yes, I would definitely recommend following the steps in the script
manually for a manual install.  It is possible to run Haven without HTTPS
and without a domain configured.

Good luck!

**Comment by betov69** [comment]
Thank you very much, so I will do it we can close the ticket, greetings
