### ISSUE TITLE
Index of

### ISSUE THREAD

**Issue by betov69** [havenweb/haven#33]
Hello, I have tried to follow the steps of the script except for the part of the certificate and the https redirection and when I try to see the server the index of it appears instead of the haven app, what step could I have omitted? Thanks and regards
![image](https://user-images.githubusercontent.com/90874504/176583697-7b9ad6cf-8adf-4f55-9156-dcc9611c2c88.png)

**Comment by mawise** [comment]
This is an old question, so Im closing it.  Feel free to let me know if you still need help!
