### ISSUE TITLE
Share without username and password

### ISSUE THREAD

**Issue by davidv171** [havenweb/haven#38]
It's not specifically stated if this is a goal at all, but is there a way to make posts globally visible? Meaning you don't need a password to see.

For example

blog.domain.com/public

**Comment by mawise** [comment]
Unauthenticated access is explicitly a non-goal for Haven.   It's possible that will change at some point, but for now I'm keeping a narrow focus on private content.

**Comment by mawise** [comment]
Closing since Haven is not pursuing public content.  I recommend Wordpress or Ghost for self-hosted public content.
