### ISSUE TITLE
Unable to make any edits when on https

### ISSUE THREAD

**Issue by Scaffale** [havenweb/haven#45]
When on https (certificate through certbot), using apache and reverse proxy:
when making some edits such as:

- login
- create post

I got this error:
```
HTTP Origin header (https://blog.<my website obscured name>.com) didn't match request.base_url (http://blog.<my website obscured name>.it) 
```
Do I have to force HTTP instead of HTTPS?

**Comment by mawise** [comment]
Hey, I think you can fix this in Nginx.  The reverse proxy is forwarding the request to rails as http.  This article should help:

https://serverok.in/nginx-rails-origin-header-didnt-match

Let me know if that takes care of it!

**Comment by Scaffale** [comment]
Yes it was my apache configuration...
just added
```
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
```
and it worked (after installing `mod_headers`)

Thanks!
