### ISSUE TITLE
How to deploy on own server?

### ISSUE THREAD

**Issue by Fastidious** [havenweb/haven#7]
How to deploy this on own server? Not on AWS, not on a Pi, just on a regular Linux VM. Thanks!

**Comment by mawise** [comment]
Given the differences between Linux platforms I can't give fool-proof deployment instructions for every platform but take a look at the two bash scripts in `deploymentscripts/lib/bash/`.  They are the steps used for installing dependencies and the Haven application in the automated AWS deployment.  There may be differences depending on your distribution.  I'll add this information to the readme.
