### ISSUE TITLE
Uploaded images sometimes missing the HREF link

### ISSUE THREAD

**Issue by elapse2039** [havenweb/haven#97]
I cant figure out why or how this happens but after when adding a 3rd or 4th uploaded image the markdown for these subsequent uploads may not have an href.

The first 2 images usually do have an href.

**Comment by mawise** [comment]
Haven will generate a smaller image to display so page loads a ~200kb image
instead of a ~5mb image (and links to the original).  But if the uploaded
image is less than a certain number of pixels across, then Haven just shows
the original image.  Might that be what you're seeing?

**Comment by elapse2039** [comment]
This seems to be the case... smaller images dont get a hyperlink.
